<script setup lang="ts"></script>

<template>
  <main class="moves-page page-shell">
    <section class="page-intro"><div><p class="eyebrow">DATABASE / MOVES</p><h1>Moves de Pokémon GO</h1><p>Dados de dano, energia e desempenho ainda dependem de uma fonte específica de Pokémon GO.</p></div><div class="result-count"><strong>—</strong><span>moves verificados</span></div></section>
    <section class="tool-panel"><p class="search-status">Nenhum provider de moves de Pokémon GO está conectado. Dados de jogos principais não são usados como substitutos.</p></section>
    <section class="moves-table" aria-label="Disponibilidade dos dados"><p class="empty-state">A database será exibida quando houver dados de moves de Pokémon GO com fonte e atualização rastreáveis.</p></section>
  </main>
</template>

<style scoped>
.moves-page{max-width:1240px;margin:auto;padding:60px clamp(20px,5vw,72px) 80px}.page-intro{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:32px}.eyebrow{color:var(--accent-bright);font-size:10px;letter-spacing:.16em;font-weight:800}.page-intro h1{margin:9px 0 8px;font-size:clamp(34px,5vw,58px);letter-spacing:-.07em}.page-intro p:last-child{color:var(--muted);font-size:14px}.result-count{display:flex;flex-direction:column;text-align:right;color:var(--muted);font-size:11px}.result-count strong{color:var(--text);font-size:28px}.tool-panel{display:flex;gap:12px;padding:14px;margin-bottom:20px;border:1px solid var(--line);border-radius:14px;background:var(--surface)}.search-field{display:flex;align-items:center;gap:10px;flex:1;color:var(--muted)}input,select{border:1px solid var(--line-strong);border-radius:9px;background:var(--surface-strong);color:var(--text);padding:12px 14px;font:inherit;font-size:12px}input{width:100%;border:0;background:transparent;outline:0}.search-field span{font-size:22px}.moves-table{overflow:hidden;border:1px solid var(--line);border-radius:14px;background:var(--surface)}.table-head,.move-row{display:grid;grid-template-columns:2.2fr 1fr 1fr .7fr .8fr 1fr 1.1fr;align-items:center;gap:14px;padding:17px 22px}.table-head{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.12em;border-bottom:1px solid var(--line)}.move-row{min-height:70px;border-bottom:1px solid var(--line);font-size:12px}.move-row:last-of-type{border:0}.move-name{display:flex;align-items:center;gap:12px}.move-icon{width:9px;height:28px;border-radius:5px;background:var(--accent-bright)}.move-icon.psychic{background:#d568c6}.move-icon.dragon{background:#6965e8}.move-icon.steel{background:#8a9cac}.move-icon.electric{background:#e6b940}.type-pill{width:max-content;padding:5px 9px;border-radius:6px;background:#383052;color:#c7b9ff;font-size:10px}.type-pill.psychic{background:#512c4f;color:#ec9fdf}.type-pill.dragon{background:#29295a;color:#aca8ff}.type-pill.steel{background:#303c48;color:#c0d2df}.type-pill.electric{background:#514522;color:#f5d666}.class-label,.users{color:var(--muted)}.efficiency b{color:#67dfb0}.efficiency small{color:var(--muted)}.users span{color:var(--accent-bright);margin-left:6px}.empty-state{padding:34px;text-align:center;color:var(--muted)}@media(max-width:760px){.page-intro{align-items:flex-start;gap:20px}.tool-panel{flex-wrap:wrap}.search-field{flex-basis:100%}.table-head{display:none}.move-row{grid-template-columns:1.7fr 1fr 1fr;padding:16px}.move-row>:nth-child(n+4){display:none}}@media(max-width:500px){.page-intro{display:block}.result-count{text-align:left;margin-top:18px}.moves-page{padding-top:36px}}
</style>
